POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Evento teste",
  "details": "Criando um evento para testes",
  "maximumAttendees": 40
}

###

POST http://localhost:3333/events/81a3f6db-45bf-4a6f-b10c-bcaf8837ac43/attendees
Content-Type: application/json

{
  "name": "Diego Fernandes",
  "email": "diego2@rocketseat.com.br"
}

###

GET http://localhost:3333/events/9e9bd979-9d10-4915-b339-3786b1634f33

###

GET http://localhost:3333/attendees/10110/badge
###

GET http://localhost:3333/attendees/10110/check-in

###

GET http://localhost:3333/events/9e9bd979-9d10-4915-b339-3786b1634f33/attendees?query=diego